### ISSUE TITLE
Lazy initialization of CUDA devices

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/yaksa#114]
At present, all CUDA devices including those not used by the main compute kernel are obtained and set up on initialization. On a machine that limits access of GPU resources to exclusive (i.e., only one process can access to GPU, the default setting of OLCF Summit), one process occupies all the CUDA devices, so creating multiple processes causes `all CUDA-capable devices are busy or unavailable` error in `yaksuri_cuda_init_hooks.c`.

There are several workarounds (e.g., setting `CUDA_VISIBLE_DEVICES`, changing the GPU resource access mode), but lazy initialization of GPU devices should be the most promising.

**Comment by pavanbalaji** [comment]
I investigated this issue a bit.  I'm not sure if lazy initialization is the right solution here.  This error tends to happen when multiple processes are set to the same device.  Without `CUDA_VISIBLE_DEVICES` set, we have no way of avoiding it, even if we do lazy initialization because the access to a device can conflict even if such access is delayed.

The only practical way to use this would be with `CUDA_VISIBLE_DEVICES`, which is what the CUDA documentation seems to suggest for multi-process systems anyway.
